### ISSUE TITLE
Categories are missing from appstream data

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.github.emmanueltouzery.cigale#2]
https://github.com/emmanueltouzery/cigale/blob/master/com.github.emmanueltouzery.cigale.desktop has no categories

Please define a proper category from https://specifications.freedesktop.org/menu-spec/latest/apa.html

**Comment by emmanueltouzery** [comment]
thank you, fixed this with https://github.com/flathub/com.github.emmanueltouzery.cigale/pull/4
